version: '3.4'

services:
  api:
    image: aster
    build:
      context: ..
      dockerfile: ./Dockerfile

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${ASTER_DATABASE_CREDENTIAL_PASSWORD}

  reverse-proxy:
    image: nginx:1.23.3
    ports:
      - "8080:80"

  redis:
    image: redis:7.0.9-alpine

  prometheus:
    image: prom/prometheus:v2.43.0

  grafana:
    image: grafana/grafana:8.5.22

volumes:
  db-data:
