# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
        - id: poetry-check
        - id: poetry-lock
        - id: poetry-export
          args: ["-f", "requirements.txt", "-o", "requirements.txt"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
    -   id: mypy
        args:
        - --config-file=pyproject.toml
        - --ignore-missing-imports

        additional_dependencies:
        - pydantic
        - strawberry-graphql
