version: '3.4'

services:
  api:
    image: aster
    build:
      context: .
      dockerfile: ./Dockerfile

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data

  reverse-proxy:
    image: nginx:1.23.3
    ports:
      - "8080:80"

volumes:
  db-data:
