version: '3.4'

services:
  api:
    image: aster
    build:
      context: .
      dockerfile: ./Dockerfile

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${ASTER_DATABASE_CREDENTIAL_PASSWORD}

  reverse-proxy:
    image: nginx:1.23.3
    ports:
      - "8080:80"

  redis:
    image: redis:7.0.9-alpine

  tracing:
    image: jaegertracing/all-in-one:1.42
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  db-data:
