"""Init database

Revision ID: 77601f6b760b
Revises:
Create Date: 2023-08-05 22:01:06.227966

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str | None = "77601f6b760b"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user__pkey")),
        sa.UniqueConstraint("username", name=op.f("user__username_key")),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["uid"], ["user_.id"], name=op.f("post_uid_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("post_pkey")),
    )
    op.create_table(
        "user_block",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("uid_blocked", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"], ["user_.id"], name=op.f("user_block_uid_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["uid_blocked"], ["user_.id"], name=op.f("user_block_uid_blocked_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_block_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_block")
    op.drop_table("post")
    op.drop_table("user_")
    # ### end Alembic commands ###
